admins/urls.py
from django.urls import path

from admins.views import index,admin_users,admin_user_create,admin_user_update,admin_user_delete, \
    admin_user_power_on,admin_user_power_off,admin_categories,admin_products

app_name='admins'

urlpatterns = [
    path('',index, name='index'),

    path('users/',admin_users, name='admin_users'),

    path('users-create/',admin_user_create, name='admin_user_create'),
    path('admin_user_update/<int:pk>',admin_user_update, name='admin_user_update'),
    path('admin_user_delete/<int:pk>',admin_user_delete, name='admin_user_delete'),
    path('admin_user_power_on/<int:pk>',admin_user_power_on, name='admin_user_power_on'),
    path('admin_user_power_off/<int:pk>',admin_user_power_off, name='admin_user_power_off'),

    path('products/',admin_products, name='admin_products'),
    path('categories/',admin_categories, name='admin_categories'),


 ]

authapp/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf import settings
from django.conf.urls.static import static

from authapp.views import login,register,logout,profile

app_name='authapp'

urlpatterns = [

    path('login/', login, name='login'),
    path('register/',register,name='register'),
    path('logout/',logout,name='logout'),
    path('profile/',profile,name='profile')

 ]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index, products #test
import authapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('',include('mainapp.urls',namespace='mainapp')),
    path('users/',include('authapp.urls',namespace='authapp')),
    path('baskets/',include('baskets.urls',namespace='baskets')),
    path('admins/',include('admins.urls',namespace='admins')),

    #path('products/', include('mainapp.urls', namespace='mainapp')),
    # path('test/', test, name='test'),

]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class User(AbstractUser):
    image=models.ImageField(upload_to='images',blank=True)
    age=models.PositiveIntegerField(default=18)

authapp/forms.py
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UserChangeForm
from django import forms
from authapp.models import User

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username','password')

    def __init__(self,*args,**kwargs):
        super(UserLoginForm,self).__init__(*args,**kwargs)
        self.fields['username'].widget.attrs['placeholder']='Введите имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        for field_name,field in self.fields.items():
            field.widget.attrs['class'] = 'form'
            field.widget.attrs['class']='form-control py-4'




class UserRegisterForm(UserCreationForm):
    class Meta:
        model =User
        fields = ('username','email','first_name', 'last_name','password1', 'password2')

    def __init__(self,*args,**kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите e-mail'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        self.fields['username'].widget.attrs['placeholder']='Введите имя пользователя'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Повторите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form'
            field.widget.attrs['class'] = 'form-control py-4'


class UserProfilerForm(UserChangeForm):

    image = forms.ImageField(widget=forms.FileInput(),required=False)
    age = forms.IntegerField(widget=forms.NumberInput(),required=False)

    class Meta:
        model =User
        fields = ('username','email','first_name', 'last_name','image','age')

    def __init__(self,*args,**kwargs):
        super(UserProfilerForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form'
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'

authapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from authapp.forms import UserRegisterForm,UserLoginForm,UserProfilerForm

# Create your views here.
from baskets.models import Basket


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username=request.POST.get('username')
            password=request.POST.get('password')
            user =auth.authenticate(username=username,password=password)
            if user.is_active:
                auth.login(request,user)
                return HttpResponseRedirect(reverse('index'))
        # else:
        #     print(form.errors)
    else:
        form = UserLoginForm()
    context={
        'title':'Geekshop | Вход',
        'form' : form,
    }
    return render(request, 'authapp/login.html',context)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Регистрация прошла успешно')
            return HttpResponseRedirect(reverse('authapp:login'))
        else:
            print(form.errors)
    else:
        form = UserRegisterForm()
    context={
        'title':'Geekshop | Регистрация',
        'form': form,
    }
    return render(request,'authapp/register.html',context)

@login_required
def profile(request):
    if request.method == 'POST':
        form=UserProfilerForm(instance=request.user, data=request.POST,files=request.FILES)
        if form.is_valid():
            messages.success(request,"Успешное сохранение профиля")
            form.save()
        else:
            messages.error(request,form.errors)
            #print(form.errors)

    total_quantity=0
    total_sum=0

    baskets = Basket.objects.filter(user=request.user)

    for basket in baskets:
        total_quantity+=basket.quantity
        total_sum+=basket.sum()

    context={
        'title':'Geetshop | Профиль',
        'form': UserProfilerForm(instance=request.user),
        'baskets': baskets,#Basket.objects.filter(user=request.user),
        'total_quantity': total_quantity,
        'total_sum': total_sum,

    }
    return render(request,'authapp/profile.html',context)


def logout(request):
    auth.logout(request)
    return render(request , 'mainapp/index.html')
    # return HttpResponseRedirect(reverse('index'))

authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{tile}}</title>
    <link href={% static 'css/auth-admin.css'%} rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src={%static 'js/auth-admin.js'%}></script>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block content %}
    <div class="col-lg-5">
                        {%if form.non_field_errors or messages%}
                        <div class="alert {%if messages%} alert-success
                        {%else%} alert-warning
                        {%endif%} alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% if messages %}
                                {%for message in messages%}
                                    {{message}}
                                {%endfor%}
                            {%else%}
                                {%for error in form.non_field_errors%}
                                    {{error}}
                                {%endfor%}
                            {%endif%}

<!--                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {%endif%}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{%url 'authapp:login'%}" method="post">
                                    {%csrf_token%}
                                    <div class="form-group">
                                        <label class="small mb-1" for={{form.username.id_for_label}}>Имя пользователя</label>
                                        {{form.username}}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for={{form.password.if_for_label}}>Пароль</label>
                                        {{form.password}}
                                    </div>
<!--                                    {{form.as_p}}-->
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                </form>

                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href={%url 'authapp:register'%}>Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
{% endblock %}

authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{%load static %}
<!-- Navigation -->

    {%block css%}
            <link href="{%static '/css/profile.css'%}" rel="stylesheet">
    {%endblock%}

    {%block content%}

        <div class="container">
                {%if form.errors or messages%}
                        <div class="alert {%if messages%} alert-success
                        {%else%} alert-warning
                        {%endif%} alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% if messages %}
                                {%for message in messages%}
                                    {{message}}
                                {%endfor%}
                            {%else%}
                                {%for error in form.errors%}
                                    {{error}}
                                {%endfor%}
                            {%endif%}

<!--                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {%endif%}

    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"

                src="{% if user.image%} {{user.image.url}} {%else%} {% static 'vendor/img/users/default_avatar.jpg'%} {%endif%}"
                class="img-thumbnail">
            </div>
            <form action="{%url 'authapp:profile'%}" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                            {{form.first_name}}
<!--                            <input class="form-control py-4" id="inputFirstName" type="text" value="Николай"/>-->
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                            {{form.last_name}}
<!--                            <input class="form-control py-4" id="inputLastName" type="text" value="Нагорный"/>-->
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{form.image}}
<!--                            <input type="file" class="custom-file-input" id="userAvatar" size="50">-->

                            <label class="custom-file-label" for="{{form.first_name.id_for_label}}">Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                        {{form.username}}
<!--                        <input class="form-control py-4" id="inputUsername" type="text"-->
<!--                               aria-describedby="usernameHelp"-->
<!--                               value="valeriy" disabled/>-->
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                            почты</label>
                        {{form.email}}
<!--                        <input class="form-control py-4" id="inputEmailAddress" type="email"-->
<!--                               aria-describedby="emailHelp"-->
<!--                               value="isp06@mail.ru" disabled/>-->
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{forme.age.id_for_label}}">Возраст</label>
                        {{form.age}}
<!--                        <input class="form-control py-4" id="inputEmailAddress" type="email"-->
<!--                               aria-describedby="emailHelp"-->
<!--                               value="isp06@mail.ru" disabled/>-->
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            {%include 'baskets/basket.html'%}
        </div>
    </div>
</div>
     {%endblock%}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html'%}
{% block content %}
    <div class="col-lg-7">
                        {%if form.errors%}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {%for error in form.errors%}
                                {{error | escape}}
                            {%endfor%}
<!--                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {%endif%}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{%url 'authapp:register'%}" method="post">
                                    {%csrf_token%}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{form.first_name.id_for_label}}>Имя</label>
                                                 {{form.first_name}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{form.last_name.id_for_label}}>Фамилия</label>
                                                {{form.last_name}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for={{form.username.id_for_label}}>Имя пользователя</label>
                                            {{form.username}}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for={{form.email.id_for_label}}>Адрес электронной
                                                почты</label>
                                            {{form.email}}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{form.password1.id_for_label}}>Пароль</label>
                                                {{form.password1}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{form.password2.id_for_label}}>Подтверждение
                                                    пароля</label>
                                                {{form.password2}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href={%url 'authapp:login'%}>Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
{% endblock %}