admins/urls.py
from django.urls import path

from admins.views import index,admin_users,admin_user_create,admin_user_update,admin_user_delete, \
    admin_user_power_on,admin_user_power_off,admin_categories,admin_products

app_name='admins'

urlpatterns = [
    path('',index, name='index'),

    path('users/',admin_users, name='admin_users'),

    path('users-create/',admin_user_create, name='admin_user_create'),
    path('admin_user_update/<int:pk>',admin_user_update, name='admin_user_update'),
    path('admin_user_delete/<int:pk>',admin_user_delete, name='admin_user_delete'),
    path('admin_user_power_on/<int:pk>',admin_user_power_on, name='admin_user_power_on'),
    path('admin_user_power_off/<int:pk>',admin_user_power_off, name='admin_user_power_off'),

    path('products/',admin_products, name='admin_products'),
    path('categories/',admin_categories, name='admin_categories'),


 ]

authapp/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf import settings
from django.conf.urls.static import static

from authapp.views import login,register,logout,profile

app_name='authapp'

urlpatterns = [

    path('login/', login, name='login'),
    path('register/',register,name='register'),
    path('logout/',logout,name='logout'),
    path('profile/',profile,name='profile')

 ]

baskets/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf import settings
from django.conf.urls.static import static
from baskets.views import basket_add, basket_remove,basket_edit

app_name='baskets'

urlpatterns = [

    path('basket_add/<int:id>/',basket_add, name='basket_add'),
    path('remove/<int:basket_id>/',basket_remove, name='basket_remove'),
    path('edit/<int:basket_id>/<int:quantity>/',basket_edit, name='basket_edit'),


 ]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index, products #test
import authapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('',include('mainapp.urls',namespace='mainapp')),
    path('users/',include('authapp.urls',namespace='authapp')),
    path('baskets/',include('baskets.urls',namespace='baskets')),
    path('admins/',include('admins.urls',namespace='admins')),

    #path('products/', include('mainapp.urls', namespace='mainapp')),
    # path('test/', test, name='test'),

]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import products #test

app_name='mainapp'

urlpatterns = [

    path('products/', products, name='products'),

     #path('test/', test, name='test'),
 ]

mainapp/models.py
from django.db import models

# Create your models here.

class Product_Category(models.Model):
    name=models.CharField(max_length=128)
    description=models.TextField(blank=True,null=True)

    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    name=models.CharField(max_length=128)
    image=models.ImageField(upload_to='product_image',blank=True)
    description=models.TextField(blank=True,null=True)
    price=models.DecimalField(max_digits=8,decimal_places=2)
    quantity=models.PositiveIntegerField(default=0)
    category=models.ForeignKey(Product_Category,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}    |   {self.category}'

    

mainapp/views.py
import json

from django.shortcuts import render
#from models import Product,Product_Category
from mainapp.models import Product,Product_Category

import os
MODULE_DIR = os.path.dirname(__file__)
# Create your views here.
def index(request):
    context={
        'title':'Geekshop',

    }
    return render(request, 'mainapp/index.html',context)


def products(request):
    #file_path=os.path.join(MODULE_DIR,'fixtures/goods.json')
    context = {
        'title': 'Geetshop | Каталог'}
   # context['products']=json.load(open(file_path,encoding='utf-8'))
    context['products']=Product.objects.all()
    context['categoryies']=Product_Category.objects.all()
    return render(request, 'mainapp/products.html', context)


# def test(request):
#     context = {
#         'title': 'geekshop_test',
#         'main_header':'Проверка контекста',
#         'welcome':'Приветствую, ',
#         'user':'Ромыч',
#         'items':[
#             {'name':'Худи черного цвета с монограммами adidas Originals','price':6900},
#             {'name': 'Синяя куртка The North Face', 'price': 23725},
#             {'name': 'Коричневый спортивный oversized-топ ASOS DESIGN', 'price': 3390},
#             {'name': 'Черный рюкзак Nike Heritage', 'price': 2340},
#             {'name': 'Черные туфли на платформе с 3 парами люверсов Dr Martens 1461 Bex', 'price': 13590},
#             {'name': 'Темно-синие широкие строгие брюки ASOS DESIGN', 'price': 2890}
#     ],
#     }
#    return render(request, 'test.html', context)

mainapp/templates/mainapp/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

        <title>{{title}}</title>

    <!-- Bootstrap core CSS -->
    <link href={% static 'vendor/bootstrap/css/bootstrap.min.css'%} rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css%}

    {%endblock%}


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop {%now "D d M Y"%}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:products'%}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {%if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href={%url 'authapp:login'%}>Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {%else%}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'authapp:profile'%}">{{user}}
                        <i class="fas fa-user-circle"></i>
                    </a>
                </li>
                {%if user.is_superuser%}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'admins:index'%}">
                        <i class="fas fa-users-cog"></i>
                    </a>
                </li>
                {%endif%}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'authapp:logout'%}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                </li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}

{%endblock%}




{%block footer%}

{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src={% static 'vendor/jquery/jquery.min.js'%}></script>
<script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="{%static 'js/basket.js'%}"></script>

<!-- FontAwesome script -->
<script src={% static 'vendor/fontawesome/fontawesome-icons.js'%} crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html'%}
{% load static %}

{%block title%}
    <title>{{title}}</title>
{%endblock%}

{% block css%}
    <link href={% static 'css/index.css' %} rel="stylesheet">
{%endblock%}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{%url 'mainapp:products'%}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{%endblock%}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html'%}
{%load static %}

    <title>{{title}}</title>

    {%block css%}
        <link href={% static 'css/products.css'%} rel="stylesheet">
    {%endblock%}


<!-- Page Content -->
{%block content%}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">GeekShop</h1>
            <div class="list-group">
                {% for category in categories%}
                <a href="#" class="list-group-item">{{category.name}}</a>
                {%endfor%}

            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src={{product.image.url}}
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{product.name}}</a>
                            </h4>
                            <h5>{{product.price}}</h5>
                            <p class="card-text">{{product.description}}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="{% url 'baskets:basket_add' product.id %}" class="btn btn-outline-success">Отправить в корзину</a>
<!--                            <a herf="{% url 'baskets:basket_add' product.id %}" class="btn btn-outline-success">Отправить в корзину</a>-->
                        </div>
                    </div>
                </div>
                {%endfor%}

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src={% static 'vendor/img/products/Blue-jacket-The-North-Face.png'%} alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Синяя куртка The North Face</a>-->
<!--                            </h4>-->
<!--                            <h5>23 725,00 руб.</h5>-->
<!--                            <p class="card-text">-->
<!--                                Гладкая ткань. Водонепроницаемое покрытие. Легкий и теплый пуховый наполнитель.-->
<!--                            </p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-danger">Удалить из корзины</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src={% static 'vendor/img/products/Brown-sports-oversized-top-ASOS-DESIGN.png'%}-->
<!--                                 alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Коричневый спортивный oversized-топ ASOS DESIGN</a>-->
<!--                            </h4>-->
<!--                            <h5>3 390,00 руб.</h5>-->
<!--                            <p class="card-text">Материал с плюшевой текстурой. Удобный и мягкий.</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src={% static 'vendor/img/products/Black-Nike-Heritage-backpack.png'%}-->
<!--                                 alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Черный рюкзак Nike Heritage</a>-->
<!--                            </h4>-->
<!--                            <h5>2 340,00 руб.</h5>-->
<!--                            <p class="card-text">Плотная ткань. Легкий материал.</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src={% static '/vendor/img/products/Black-Dr-Martens-shoes.png'%}-->
<!--                                 alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Черные туфли на платформе с 3 парами люверсов Dr Martens 1461 Bex</a>-->
<!--                            </h4>-->
<!--                            <h5>13 590,00 руб.</h5>-->
<!--                            <p class="card-text">Гладкий кожаный верх. Натуральный материал.</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src={% static 'vendor/img/products/Dark-blue-wide-leg-ASOs-DESIGN-trousers.png'%}-->
<!--                                 alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Темно-синие широкие строгие брюки ASOS DESIGN</a>-->
<!--                            </h4>-->
<!--                            <h5>2 890,00 руб.</h5>-->
<!--                            <p class="card-text">Легкая эластичная ткань сирсакер Фактурная ткань.</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{%endblock%}
<!-- /.container -->

<!-- Footer -->
{%block footer%}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
    </div>
    <!-- /.container -->
</footer>
{%endblock%}

<!-- Bootstrap core JavaScript -->
<script src={% static 'vendor/jquery/jquery.min.js'%}></script>
<script src={% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}></script>

<!-- FontAwesome script -->
<script src={% static 'vendor/fontawesome/fontawesome-icons.js'%} crossorigin="anonymous"></script>

mainapp/templates/mainapp/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>
<h1>{{main_header}}</h1>

<span>{{welcome}}</span>
<span>{{user}}</span>

{%for i in items%}
    {% if i.price > 5000 %}
        <p style="color:red;" >{{i.name}}, {{i.price}}</p>
    {% else %}
        <p>{{i.name}}, {{i.price}}<br>
    {%endif%}
{%endfor%}

</body>
</html>