admins/urls.py
from django.urls import path

from admins.views import index,admin_users,admin_user_create,admin_user_update,admin_user_delete, \
    admin_user_power_on,admin_user_power_off,admin_categories,admin_products

app_name='admins'

urlpatterns = [
    path('',index, name='index'),

    path('users/',admin_users, name='admin_users'),

    path('users-create/',admin_user_create, name='admin_user_create'),
    path('admin_user_update/<int:pk>',admin_user_update, name='admin_user_update'),
    path('admin_user_delete/<int:pk>',admin_user_delete, name='admin_user_delete'),
    path('admin_user_power_on/<int:pk>',admin_user_power_on, name='admin_user_power_on'),
    path('admin_user_power_off/<int:pk>',admin_user_power_off, name='admin_user_power_off'),

    path('products/',admin_products, name='admin_products'),
    path('categories/',admin_categories, name='admin_categories'),


 ]

authapp/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf import settings
from django.conf.urls.static import static

from authapp.views import login,register,logout,profile

app_name='authapp'

urlpatterns = [

    path('login/', login, name='login'),
    path('register/',register,name='register'),
    path('logout/',logout,name='logout'),
    path('profile/',profile,name='profile')

 ]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index, products #test
import authapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('',include('mainapp.urls',namespace='mainapp')),
    path('users/',include('authapp.urls',namespace='authapp')),
    path('baskets/',include('baskets.urls',namespace='baskets')),
    path('admins/',include('admins.urls',namespace='admins')),

    #path('products/', include('mainapp.urls', namespace='mainapp')),
    # path('test/', test, name='test'),

]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins/templates/admin-categories-read.html
{%extends 'base.html'%}

{%block content%}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        {{title}}
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Категория</th>
                                    <th>Описание</th>

                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Категория</th>
                                    <th>Описание</th>

                                </tr>
                                </tfoot>
                                <tbody>
                                {% for category in categories%}
                                <tr>
<!--                                    <th><a href="{%url 'admins:admin_user_update' user.id %}" style="color: dodgerblue">{{user.username}}</a></th>-->
                                    <th>{{category.name}}</th>
                                    <th>{{category.description}}</th>


<!--                                    <td class="text-center">-->
<!--                                        {% if user.is_staff%}-->
<!--                                        <i class="fas fa-check-circle"></i>-->
<!--                                        {%else%}-->
<!--                                        <i class="fas fa-times-circle"></i>-->
<!--                                        {%endif%}-->
<!--                                    </td>-->
<!--                                    <td class="text-center">-->
<!--                                        {% if category.is_active%}-->
<!--                                        <i class="fas fa-check-circle"></i>-->
<!--                                        {%else%}-->
<!--                                        <i class="fas fa-times-circle"></i>-->
<!--                                        {%endif%}-->
<!--                                    </td>-->
                                </tr>
                                {%endfor%}
<!--                                <tr>-->
<!--                                    <td><a href="#" style="color: dodgerblue">test</a></td>-->
<!--                                    <td></td>-->
<!--                                    <td></td>-->
<!--                                    <td></td>-->
<!--                                    <td class="text-center"><i class="fas fa-check-circle"></i></td>-->
<!--                                    <td class="text-center"><i class="fas fa-check-circle"></i></td>-->
<!--                                </tr>-->
<!--                                <tr>-->
<!--                                    <td><a href="admin-users-update-delete.html" style="color: dodgerblue">nikolay</a></td>-->
<!--                                    <td>Nikolay</td>-->
<!--                                    <td>Nagornyy</td>-->
<!--                                    <td>isp06.ru</td>-->
<!--                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>-->
<!--                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>-->
<!--                                </tr>-->
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href=" ">
                            <button class="btn btn-success">Создать категорию товаров</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{%endblock%}

admins/templates/admin-products-read.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        {{title}}
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Название</th>
                                    <th>Картинка</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Категория</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Название</th>
                                    <th>Картинка</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Категория</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for product in products%}
                                <tr>
                                    <th><a href="#" style="color: dodgerblue">{{product.name}}</a></th>
                                    <th><img  height="50" src="{{product.image.url}}"></th>
<!--                                    <th>{{product.image.url}}</th>-->
                                    <th>{{product.description}}</th>
                                    <th>{{product.price}}</th>
                                    <th>{{product.quantity}}</th>
                                    <th>{{product.category}}</th>

<!--                                    <td class="text-center">-->
<!--                                        {% if user.is_staff%}-->
<!--                                        <i class="fas fa-check-circle"></i>-->
<!--                                        {%else%}-->
<!--                                        <i class="fas fa-times-circle"></i>-->
<!--                                        {%endif%}-->
<!--                                    </td>-->
<!--                                    <td class="text-center">-->
<!--                                        {% if user.is_active%}-->
<!--                                        <i class="fas fa-check-circle"></i>-->
<!--                                        {%else%}-->
<!--                                        <i class="fas fa-times-circle"></i>-->
<!--                                        {%endif%}-->
<!--                                    </td>-->
                                </tr>
                                {%endfor%}
<!--                                <tr>-->
<!--                                    <td><a href="#" style="color: dodgerblue">test</a></td>-->
<!--                                    <td></td>-->
<!--                                    <td></td>-->
<!--                                    <td></td>-->
<!--                                    <td class="text-center"><i class="fas fa-check-circle"></i></td>-->
<!--                                    <td class="text-center"><i class="fas fa-check-circle"></i></td>-->
<!--                                </tr>-->
<!--                                <tr>-->
<!--                                    <td><a href="admin-users-update-delete.html" style="color: dodgerblue">nikolay</a></td>-->
<!--                                    <td>Nikolay</td>-->
<!--                                    <td>Nagornyy</td>-->
<!--                                    <td>isp06.ru</td>-->
<!--                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>-->
<!--                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>-->
<!--                                </tr>-->
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="# ">
                            <button class="btn btn-success">Создать продукт</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{%endblock%}

admins/templates/admin-users-create.html
{%extends 'base.html'%}

{%block content%}
    <div id="layoutSidenav_content">
        <main>

            <div class="container-fluid">
                <h1 class="mt-4">Создание пользователя</h1>

                <form action="{%url 'admins:admin_user_create'%}" method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>

                                {{form.first_name}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                {{form.last_name}}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
<!--                                <input type="file" class="custom-file-input" id="userAvatar" size="50">-->
                                <label class="custom-file-label" for="{{form.image.id_for_label}}">Выберите изображение</label>
                                {{form.image}}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                           {{form.username}}
                        </div>
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                                почты</label>
                            {{form.email}}
                        </div>
                        <div class="col-lg-2">
                            <label class="small mb-1" for="{{form.age.id_for_label}}">Возраст</label>
                            {{form.age}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.password1.id_for_label}}">Пароль</label>
                            {{form.password1}}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.password2.id_for_label}}">Повторите пароль</label>
                            {{form.password2}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{%endblock%}

admins/templates/admin-users-read.html
{%extends 'base.html'%}

{%block content%}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        {{title}}
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for user in users%}
                                <tr>
                                    <th><a href="{%url 'admins:admin_user_update' user.id %}" style="color: dodgerblue">{{user.username}}</a></th>
                                    <th>{{user.first_name}}</th>
                                    <th>{{user.last_name}}</th>
                                    <th>{{user.email}}</th>

                                    <td class="text-center">
                                        {% if user.is_staff%}
                                        <i class="fas fa-check-circle"></i>
                                        {%else%}
                                        <i class="fas fa-times-circle"></i>
                                        {%endif%}
                                    </td>
                                    <td class="text-center">
                                        {% if user.is_active%}
                                        <i class="fas fa-check-circle"></i>
                                        {%else%}
                                        <i class="fas fa-times-circle"></i>
                                        {%endif%}
                                    </td>
                                </tr>
                                {%endfor%}
<!--                                <tr>-->
<!--                                    <td><a href="#" style="color: dodgerblue">test</a></td>-->
<!--                                    <td></td>-->
<!--                                    <td></td>-->
<!--                                    <td></td>-->
<!--                                    <td class="text-center"><i class="fas fa-check-circle"></i></td>-->
<!--                                    <td class="text-center"><i class="fas fa-check-circle"></i></td>-->
<!--                                </tr>-->
<!--                                <tr>-->
<!--                                    <td><a href="admin-users-update-delete.html" style="color: dodgerblue">nikolay</a></td>-->
<!--                                    <td>Nikolay</td>-->
<!--                                    <td>Nagornyy</td>-->
<!--                                    <td>isp06.ru</td>-->
<!--                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>-->
<!--                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>-->
<!--                                </tr>-->
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{%url 'admins:admin_user_create'%} ">
                            <button class="btn btn-success">Создать пользователя</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{%endblock%}

admins/templates/admin-users-update-delete.html
{%extends 'base.html'%}

{%block content%}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <div class="card-body">
                    <form action="{%url 'admins:admin_user_update' user_selected.id %}" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                                    {{form.first_name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                    {{form.last_name}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{form.image}}
                                    <label class="custom-file-label" for="{{form.image.id_for_label}}">Выберите изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-5">
                                <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                                {{form.username}}
                            </div>
                            <div class="col-lg-5">
                                <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                                    почты</label>
                                {{form.email}}
                            </div>
                             <div class="col-lg-2">
                            <label class="small mb-1" for="{{form.age.id_for_label}}">Возраст</label>
                            {{form.age}}
                        </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                         </form>

                    {% if not user_selected.is_active%}

                    <form action="{%url 'admins:admin_user_power_on' user_selected.id%}" method="post" enctype="multipart/form-data">
                            {%csrf_token%}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-success  btn-block" type="submit" value="Включить">
                            </div>
                        </div>
                        </form>

                    {%else%}

                        <form action="{%url 'admins:admin_user_power_off' user_selected.id%}" method="post" enctype="multipart/form-data">
                            {%csrf_token%}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-warning  btn-block" type="submit" value="Отключить">
                            </div>
                        </div>
                        </form>
                    {%endif%}

                        </form>
                        <form action="{%url 'admins:admin_user_delete' user_selected.id%}" method="post" enctype="multipart/form-data">
                            {%csrf_token%}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                        </form>

                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{%endblock%}

admins/templates/admin.html
{%extends 'base.html'%}

{%block content%}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{%endblock%}

admins/templates/admin1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Я - АДМИНКА</h1>
</body>
</html>

admins/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{title}}</title>
    <link href="{% static 'css/auth-admin.css'%}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{%url 'index'%}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{%url 'authapp:logout'%}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    {% include 'includes/siberia_bar.html'%}
    {%block content %}
    {%endblock%}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{%  static 'js/auth-admin.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js'%} "></script>
</body>
</html>